import io
import json
import os
from datetime import datetime

from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image as RLImage, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

from docx import Document
from docx.shared import Inches, RGBColor


def _load_steps(step_log_raw) -> list:
    if not step_log_raw:
        return []
    if isinstance(step_log_raw, list):
        return step_log_raw
    return json.loads(step_log_raw)


def _to_rgb_buf(path: str) -> io.BytesIO | None:
    """Open an image, flatten to RGB (handling RGBA/P), return PNG BytesIO."""
    try:
        with PILImage.open(path) as img:
            if img.mode in ("RGBA", "LA"):
                bg = PILImage.new("RGB", img.size, (255, 255, 255))
                bg.paste(img, mask=img.split()[-1])
                img = bg
            elif img.mode != "RGB":
                img = img.convert("RGB")
            buf = io.BytesIO()
            img.save(buf, format="PNG")
            buf.seek(0)
            return buf
    except Exception:
        return None


def _rl_image(path: str, max_width_cm: float):
    if not os.path.isfile(path):
        return None
    buf = _to_rgb_buf(path)
    if buf is None:
        return None
    img = RLImage(buf)
    max_w = max_width_cm * cm
    if img.drawWidth > max_w:
        scale = max_w / img.drawWidth
        img.drawWidth = max_w
        img.drawHeight = img.drawHeight * scale
    return img


def export_pdf(run: dict, results: list,
               screenshots_dir: str = "data/screenshots") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(f"Test Run Report — {run['app']}", styles["Title"]))
    story.append(Spacer(1, 0.3 * cm))
    for line in [
        f"Environment: {run['environment']}",
        f"Run ID: {run['id'][:8]}",
        f"Started: {run.get('started_at') or '—'}",
        f"Status: {run['status'].upper()}",
    ]:
        story.append(Paragraph(line, styles["Normal"]))
    story.append(Spacer(1, 0.6 * cm))

    for result in results:
        steps = _load_steps(result.get("step_log"))
        test_type = "browser" if steps else "availability/api"

        story.append(Paragraph(f"Test: {result['test_name']}", styles["Heading2"]))
        story.append(Paragraph(
            f"Type: {test_type} | Status: {result['status']} | Duration: {result.get('duration_ms', 0)}ms",
            styles["Normal"],
        ))

        if result.get("error_msg"):
            story.append(Paragraph(f"Error: {result['error_msg']}", styles["Normal"]))

        if steps:
            table_data = [["Step", "Status", "Duration", "Error"]]
            for s in steps:
                table_data.append([
                    s.get("step", ""),
                    s.get("status", ""),
                    f"{s.get('duration_ms', 0)}ms",
                    s.get("error") or "",
                ])
            tbl = Table(table_data, colWidths=[7 * cm, 2 * cm, 2.5 * cm, 5 * cm])
            tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#374151")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d1d5db")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                 [colors.white, colors.HexColor("#f9fafb")]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]))
            story.append(Spacer(1, 0.2 * cm))
            story.append(tbl)
            story.append(Spacer(1, 0.3 * cm))

        if result.get("screenshot"):
            img = _rl_image(os.path.join(screenshots_dir, result["screenshot"]), 14)
            if img:
                story.append(Paragraph("Screenshot at failure:", styles["Normal"]))
                story.append(img)
                story.append(Spacer(1, 0.2 * cm))

        for s in steps:
            if s.get("screenshot"):
                img = _rl_image(os.path.join(screenshots_dir, s["screenshot"]), 12)
                if img:
                    story.append(Paragraph(f"Step screenshot: {s.get('step', '')}", styles["Normal"]))
                    story.append(img)
                    story.append(Spacer(1, 0.2 * cm))

        story.append(Spacer(1, 0.5 * cm))

    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph(
        f"Generated by Web Testing Harness on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        styles["Normal"],
    ))

    doc.build(story)
    return buf.getvalue()


def export_docx(run: dict, results: list,
                screenshots_dir: str = "data/screenshots") -> bytes:
    doc = Document()

    doc.add_heading(f"Test Run Report — {run['app']}", 0)
    meta = doc.add_paragraph()
    meta.add_run(f"Environment: {run['environment']}\n")
    meta.add_run(f"Run ID: {run['id'][:8]}\n")
    meta.add_run(f"Started: {run.get('started_at') or '—'}\n")
    meta.add_run(f"Status: {run['status'].upper()}")
    doc.add_paragraph()

    for result in results:
        steps = _load_steps(result.get("step_log"))
        test_type = "browser" if steps else "availability/api"

        doc.add_heading(f"Test: {result['test_name']}", level=2)
        doc.add_paragraph(
            f"Type: {test_type} | Status: {result['status']} | Duration: {result.get('duration_ms', 0)}ms"
        )

        if result.get("error_msg"):
            err_p = doc.add_paragraph()
            err_run = err_p.add_run(f"Error: {result['error_msg']}")
            err_run.font.color.rgb = RGBColor(0xC0, 0x00, 0x00)

        if steps:
            tbl = doc.add_table(rows=1, cols=4)
            tbl.style = "Table Grid"
            hdr = tbl.rows[0].cells
            for i, heading in enumerate(["Step", "Status", "Duration", "Error"]):
                hdr[i].text = heading
            for s in steps:
                row = tbl.add_row().cells
                row[0].text = s.get("step", "")
                row[1].text = s.get("status", "")
                row[2].text = f"{s.get('duration_ms', 0)}ms"
                row[3].text = s.get("error") or ""
            doc.add_paragraph()

        if result.get("screenshot"):
            path = os.path.join(screenshots_dir, result["screenshot"])
            buf = _to_rgb_buf(path) if os.path.isfile(path) else None
            if buf:
                doc.add_paragraph("Screenshot at failure:")
                doc.add_picture(buf, width=Inches(5))
                doc.add_paragraph()

        for s in steps:
            if s.get("screenshot"):
                path = os.path.join(screenshots_dir, s["screenshot"])
                buf = _to_rgb_buf(path) if os.path.isfile(path) else None
                if buf:
                    doc.add_paragraph(f"Step screenshot: {s.get('step', '')}")
                    doc.add_picture(buf, width=Inches(5))
                    doc.add_paragraph()

    doc.add_paragraph()
    doc.add_paragraph(
        f"Generated by Web Testing Harness on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
